server:
  port: 8080

spring:
  application:
    name: smart-ecommerce-app

  # ===============================
  # PostgreSQL Configuration (SQL)
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # ===============================
  # MongoDB Configuration (NoSQL)
  # ===============================
  data:
    mongodb:
      uri: mongodb://localhost:27017/smart_ecommerce
      auto-index-creation: true

# ===============================
# Logging (Optional but Recommended)
# ===============================
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.hibernate.SQL: DEBUG

# ===============================
# Actuator (Optional ? Monitoring)
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: health,info
